### ISSUE TITLE
Using --no-push should not result in file paths/line numbers

### ISSUE THREAD

**Issue by jsoref** [revsys/vinnie#10]
Expected user facing output shouldn't have stack traces nor should it have filenames & line numbers. This change suppresses the latter.

#### Steps
```sh
vinnie --no-push patch
```
#### Actual results
```py
...pyenv/lib/python3.7/site-packages/vinnie/base.py:92: UserWarning: Skipping push.
  warnings.warn("Skipping push.", UserWarning)
1.0.2
```
#### Expected results
Do not include any paths/line numbers. The user asked for a behavior, and the behavior is being performed, this is not unexpected, and thus does not merit developer oriented warning style output.

**Comment by fcurella** [comment]
I agree, shouldn't be a warning if that's what the user asked.
